# C?u hình H2 ch?y trên RAM
spring.datasource.url=jdbc:h2:mem:fuguide_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cho phép Hibernate t? t?o b?ng t? Entity
spring.jpa.hibernate.ddl-auto=update

# (Tùy ch?n) ?? b?n có th? vào xem b?ng d? li?u qua trình duy?t
spring.h2.console.enabled=true