spring.web.locale=en_US

# Optional: direct path to Firebase service account JSON file.
# Example:
# firebase.credentials.path=C:/Users/admin/Downloads/firebase-service-account.json
firebase.credentials.path="C:/Users/admin/Downloads/fuguide-29fe0-firebase-adminsdk-fbsvc-29695198dd.json"

# Optional: explicit Firebase project id.
# Example:
# firebase.project-id=your-firebase-project-id
firebase.project-id=fuguide-29fe0